name: shortener

volumes:
  postgres:

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh:ro
    ports:
      - "5433:5432"
    restart : always
    profiles:
      - app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATABASE: urldb

  url_service:
    container_name: url_service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-docker
    ports:
      - "8080:8080"
    #environment:
    #  - DB_DSN=postgres://postgres:1234@postgres:5432/urldb?sslmode=disable
    #  - APP_URL=http://localhost:8080
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - app
    restart: always
    #networks:
    #  - url_network