// Code generated by MockGen. DO NOT EDIT.
// Source: internal/middleware/validator/validation.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ValidateKey mocks base method.
func (m *MockValidator) ValidateKey(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateKey", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateKey indicates an expected call of ValidateKey.
func (mr *MockValidatorMockRecorder) ValidateKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateKey", reflect.TypeOf((*MockValidator)(nil).ValidateKey), key)
}

// ValidateKeys mocks base method.
func (m *MockValidator) ValidateKeys(keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateKeys", keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateKeys indicates an expected call of ValidateKeys.
func (mr *MockValidatorMockRecorder) ValidateKeys(keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateKeys", reflect.TypeOf((*MockValidator)(nil).ValidateKeys), keys)
}

// ValidateURL mocks base method.
func (m *MockValidator) ValidateURL(URL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateURL", URL)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateURL indicates an expected call of ValidateURL.
func (mr *MockValidatorMockRecorder) ValidateURL(URL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateURL", reflect.TypeOf((*MockValidator)(nil).ValidateURL), URL)
}

// ValidateURLs mocks base method.
func (m *MockValidator) ValidateURLs(URLs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateURLs", URLs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateURLs indicates an expected call of ValidateURLs.
func (mr *MockValidatorMockRecorder) ValidateURLs(URLs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateURLs", reflect.TypeOf((*MockValidator)(nil).ValidateURLs), URLs)
}
